version: 2.1

workflows:
  build-push:
    jobs:
      - build:
          matrix:
            parameters:
              build: ["--auto"]

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    parameters:
      build:
        type: string
        default:
    steps:
      - run:
          name: null-launch
          command: |
            echo test
